Refactoring Report generation (wip)

diff --git a/mods/run.d/BIGWIG b/mods/run.d/BIGWIG
--- a/mods/run.d/BIGWIG
+++ b/mods/run.d/BIGWIG
@@ -8,10 +8,30 @@
 ################################################################################
 
 if [ -n "$RUNBIGWIG" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_BIGWIG" ] || [ -z "$NODES_BIGWIG" ] || [ -z "$CPU_BIGWIG" ] || [ -z "$MEMORY_BIGWIG" ] || [ -z "$WALLTIME_BIGWIG" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
     
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_BIGWIG -i $INPUT_BIGWIG -e $ASD.bam \
-        -n $NODES_BIGWIG -c $CPU_BIGWIG -m $MEMORY_BIGWIG"G" -w $WALLTIME_BIGWIG \
-        --command "${NGSANE_BASE}/mods/bigwig.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BIGWIG"
-            
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_BIGWIG" ] || [ -z "$NODES_BIGWIG" ] || [ -z "$CPU_BIGWIG" ] || [ -z "$MEMORY_BIGWIG" ] || [ -z "$WALLTIME_BIGWIG" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+        
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_BIGWIG -i $INPUT_BIGWIG -e $ASD.bam \
+            -n $NODES_BIGWIG -c $CPU_BIGWIG -m $MEMORY_BIGWIG"G" -w $WALLTIME_BIGWIG \
+            --command "${NGSANE_BASE}/mods/bigwig.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BIGWIG"
+
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+    
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Bigwig" "$TASK_BIGWIG" "bigwig.sh" ".bw"
+
+        echo "[NOTE] the bigwig.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER  
+        
+    fi
+       
 fi
diff --git a/mods/run.d/BLUE b/mods/run.d/BLUE
--- a/mods/run.d/BLUE
+++ b/mods/run.d/BLUE
@@ -8,10 +8,31 @@
 ################################################################################
 
 if [ -n "$RUNBLUE" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_BLUE" ] || [ -z "$NODES_BLUE" ] || [ -z "$CPU_BLUE" ] || [ -z "$MEMORY_BLUE" ] || [ -z "$WALLTIME_BLUE" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
     
-    $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_BLUE -i $INPUT_BLUE -e $READONE.$FASTQ \
-        -n $NODES_BLUE -c $CPU_BLUE -m $MEMORY_BLUE"G" -w $WALLTIME_BLUE \
-        --command "${NGSANE_BASE}/mods/blue.sh -k $CONFIG -f <FILE> -o $INPUT_BLUE/<DIR>"_"$TASK_BLUE/" 
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-fi
+        # check if resources are properly defined
+        if [ -z "$TASK_BLUE" ] || [ -z "$NODES_BLUE" ] || [ -z "$CPU_BLUE" ] || [ -z "$MEMORY_BLUE" ] || [ -z "$WALLTIME_BLUE" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+        
+        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_BLUE -i $INPUT_BLUE -e $READONE.$FASTQ \
+            -n $NODES_BLUE -c $CPU_BLUE -m $MEMORY_BLUE"G" -w $WALLTIME_BLUE \
+            --command "${NGSANE_BASE}/mods/blue.sh -k $CONFIG -f <FILE> -o $INPUT_BLUE/<DIR>"_"$TASK_BLUE/" 
+
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Blue" "$TASK_BLUE" "blue.sh"
+
+        echo "[NOTE] the blue.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER  
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/BOWTIE b/mods/run.d/BOWTIE
--- a/mods/run.d/BOWTIE
+++ b/mods/run.d/BOWTIE
@@ -8,21 +8,54 @@
 ################################################################################
 
 if [ -n "$RUNBOWTIE" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_BOWTIE" ] || [ -z "$NODES_BOWTIE" ] || [ -z "$CPU_BOWTIE" ] || [ -z "$MEMORY_BOWTIE" ] || [ -z "$WALLTIME_BOWTIE" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
-
-    if [ ! -f ${FASTA%.*}.1.ebwt ];then
-        # submit job for index generation if necessary
-        INDEXJOBIDS=$(
-            $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_BOWTIE -i $INPUT_BOWTIE -e $READONE.$FASTQ \
-            -n $NODES_BOWTIE -c $CPU_BOWTIE -m $MEMORY_BOWTIE"G" \
-            -w $WALLTIME_BOWTIE --commontask indexGenome \
-            --command "${NGSANE_BASE}/mods/bowtieIndex.sh -k $CONFIG"
-        ) && echo -e "$INDEXJOBIDS"
-        INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
-    else
-        INDEXJOBIDS=$NGSANE_WAITFORJOB 
-    fi
     
-    $QSUB $ARMED -k $CONFIG -t $TASK_BOWTIE -i $INPUT_BOWTIE -e $READONE.$FASTQ -n $NODES_BOWTIE -c $CPU_BOWTIE -m $MEMORY_BOWTIE"G" -w $WALLTIME_BOWTIE $INDEXJOBIDS \
-        --command "${NGSANE_BASE}/mods/bowtie.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BOWTIE --rgsi <DIR>"        
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_BOWTIE" ] || [ -z "$NODES_BOWTIE" ] || [ -z "$CPU_BOWTIE" ] || [ -z "$MEMORY_BOWTIE" ] || [ -z "$WALLTIME_BOWTIE" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        if [ ! -f ${FASTA%.*}.1.ebwt ];then
+            # submit job for index generation if necessary
+            INDEXJOBIDS=$(
+                $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_BOWTIE -i $INPUT_BOWTIE -e $READONE.$FASTQ \
+                -n $NODES_BOWTIE -c $CPU_BOWTIE -m $MEMORY_BOWTIE"G" \
+                -w $WALLTIME_BOWTIE --commontask indexGenome \
+                --command "${NGSANE_BASE}/mods/bowtieIndex.sh -k $CONFIG"
+            ) && echo -e "$INDEXJOBIDS"
+            INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
+        else
+            INDEXJOBIDS=$NGSANE_WAITFORJOB 
+        fi
+        
+        $QSUB $ARMED -k $CONFIG -t $TASK_BOWTIE -i $INPUT_BOWTIE -e $READONE.$FASTQ -n $NODES_BOWTIE -c $CPU_BOWTIE -m $MEMORY_BOWTIE"G" -w $WALLTIME_BOWTIE $INDEXJOBIDS \
+            --command "${NGSANE_BASE}/mods/bowtie.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BOWTIE --rgsi <DIR>"        
+
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "BOWTIE" "$TASK_BOWTIE" "bowtie.sh" "$ASD.bam"
+
+        # add as many tables as needed. One table per result file
+        NGSANE_REPORT_TABLE "$TASK_BOWTIE" \
+            "$OUT/<DIR>/$TASK_BOWTIE"  \
+            "$ASD.bam.stats" \
+            "PATTERN:Total reads:sed -n 1p | cut -d' ' -f 1" \
+            "PATTERN:Qfail:sed -n 1p | cut -d' ' -f 3" \
+            "PATTERN:Duplicates:sed -n 2p | cut -d' ' -f 1" \
+            "CALCULATE:Duplicates %:#4*100/#2" \
+            "PATTERN:Mapped:sed -n 3p | cut -d' ' -f 1" \
+            "CALCULATE:Mapped %:#6*100/#2" \
+            "PATTERN:Paired:sed -n 7p | cut -d' ' -f 1" \
+            "CALCULATE:Paired %:#8*100/#2" \
+            "PATTERN:Singletons:sed -n 9p | cut -d' ' -f 1" 
+        
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+        
+    fi
 fi
diff --git a/mods/run.d/BOWTIE2 b/mods/run.d/BOWTIE2
--- a/mods/run.d/BOWTIE2
+++ b/mods/run.d/BOWTIE2
@@ -7,22 +7,55 @@
 # OUT: $OUT/$dir/bowtie2/*$ASD.bam
 ################################################################################
 if [ -n "$RUNBOWTIE2" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_BOWTIE2" ] || [ -z "$NODES_BOWTIE2" ] || [ -z "$CPU_BOWTIE2" ] || [ -z "$MEMORY_BOWTIE2" ] || [ -z "$WALLTIME_BOWTIE2" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
     
-    if [ ! -f ${FASTA%.*}.1.bt2 ];then
-        # submit job for index generation if necessary
-        INDEXJOBIDS=$(
-            $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_BOWTIE2 -i $INPUT_BOWTIE2 -e $READONE.$FASTQ \
-            -n $NODES_BOWTIE2 -c $CPU_BOWTIE2 -m $MEMORY_BOWTIE2"G" \
-            -w $WALLTIME_BOWTIE2 --commontask indexGenome \
-            --command "${NGSANE_BASE}/mods/bowtie2Index.sh -k $CONFIG"
-        ) && echo -e "$INDEXJOBIDS"
-        INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
-    else
-        INDEXJOBIDS=$NGSANE_WAITFORJOB 
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_BOWTIE2" ] || [ -z "$NODES_BOWTIE2" ] || [ -z "$CPU_BOWTIE2" ] || [ -z "$MEMORY_BOWTIE2" ] || [ -z "$WALLTIME_BOWTIE2" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        if [ ! -f ${FASTA%.*}.1.bt2 ];then
+            # submit job for index generation if necessary
+            INDEXJOBIDS=$(
+                $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_BOWTIE2 -i $INPUT_BOWTIE2 -e $READONE.$FASTQ \
+                -n $NODES_BOWTIE2 -c $CPU_BOWTIE2 -m $MEMORY_BOWTIE2"G" \
+                -w $WALLTIME_BOWTIE2 --commontask indexGenome \
+                --command "${NGSANE_BASE}/mods/bowtie2Index.sh -k $CONFIG"
+            ) && echo -e "$INDEXJOBIDS"
+            INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
+        else
+            INDEXJOBIDS=$NGSANE_WAITFORJOB 
+        fi
+        
+        $QSUB $ARMED -k $CONFIG -t $TASK_BOWTIE2 -i $INPUT_BOWTIE2 -e $READONE.$FASTQ -n $NODES_BOWTIE2 -c $CPU_BOWTIE2 -m $MEMORY_BOWTIE2"G" -w $WALLTIME_BOWTIE2 $INDEXJOBIDS \
+    	       --command "${NGSANE_BASE}/mods/bowtie2.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BOWTIE2 --rgsi <DIR>"
+
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Bowtie2" "$TASK_BOWTIE2" "bowtie2.sh" "$ASD.bam"
+
+        # add as many tables as needed. One table per result file
+        NGSANE_REPORT_TABLE "$TASK_BOWTIE2" \
+            "$OUT/<DIR>/$TASK_BOWTIE2"  \
+            "$ASD.bam.stats" \
+            "PATTERN:Total reads:sed -n 1p | cut -d' ' -f 1" \
+            "PATTERN:Qfail:sed -n 1p | cut -d' ' -f 3" \
+            "PATTERN:Duplicates:sed -n 2p | cut -d' ' -f 1" \
+            "CALCULATE:Duplicates %:#4*100/#2" \
+            "PATTERN:Mapped:sed -n 3p | cut -d' ' -f 1" \
+            "CALCULATE:Mapped %:#6*100/#2" \
+            "PATTERN:Paired:sed -n 7p | cut -d' ' -f 1" \
+            "CALCULATE:Paired %:#8*100/#2" \
+            "PATTERN:Singletons:sed -n 9p | cut -d' ' -f 1" 
+        
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+        
     fi
-    
-    $QSUB $ARMED -k $CONFIG -t $TASK_BOWTIE2 -i $INPUT_BOWTIE2 -e $READONE.$FASTQ -n $NODES_BOWTIE2 -c $CPU_BOWTIE2 -m $MEMORY_BOWTIE2"G" -w $WALLTIME_BOWTIE2 $INDEXJOBIDS \
-	       --command "${NGSANE_BASE}/mods/bowtie2.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BOWTIE2 --rgsi <DIR>"
-      
+
 fi
diff --git a/mods/run.d/BWA b/mods/run.d/BWA
--- a/mods/run.d/BWA
+++ b/mods/run.d/BWA
@@ -8,22 +8,55 @@
 ################################################################################
 
 if [ -n "$RUNBWA" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_BWA" ] || [ -z "$NODES_BWA" ] || [ -z "$CPU_BWA" ] || [ -z "$MEMORY_BWA" ] || [ -z "$WALLTIME_BWA" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    if [ ! -f $FASTA.bwt ];then
-        # submit job for index generation if necessary
-        JOBIDS=$(
-            $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_BWA -i $INPUT_BWA -e $READONE.$FASTQ \
-            -n $NODES_BWA -c $CPU_BWA -m $MEMORY_BWA"G" \
-            -w $WALLTIME_BWA --commontask indexGenome \
-            --command "${NGSANE_BASE}/mods/bwaIndex.sh -k $CONFIG"
-        ) && echo -e "$JOBIDS"
-        JOBIDS=$(waitForJobIds "$JOBIDS")
-    else
-        JOBIDS=$NGSANE_WAITFORJOB
+        # check if resources are properly defined
+        if [ -z "$TASK_BWA" ] || [ -z "$NODES_BWA" ] || [ -z "$CPU_BWA" ] || [ -z "$MEMORY_BWA" ] || [ -z "$WALLTIME_BWA" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        if [ ! -f $FASTA.bwt ];then
+            # submit job for index generation if necessary
+            JOBIDS=$(
+                $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_BWA -i $INPUT_BWA -e $READONE.$FASTQ \
+                -n $NODES_BWA -c $CPU_BWA -m $MEMORY_BWA"G" \
+                -w $WALLTIME_BWA --commontask indexGenome \
+                --command "${NGSANE_BASE}/mods/bwaIndex.sh -k $CONFIG"
+            ) && echo -e "$JOBIDS"
+            JOBIDS=$(waitForJobIds "$JOBIDS")
+        else
+            JOBIDS=$NGSANE_WAITFORJOB
+        fi
+    
+        $QSUB $ARMED -k $CONFIG -t $TASK_BWA -i $INPUT_BWA -e $READONE.$FASTQ \
+            -n $NODES_BWA -c $CPU_BWA -m $MEMORY_BWA"G" -w $WALLTIME_BWA $JOBIDS \
+            --command "${NGSANE_BASE}/mods/bwa.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BWA --rgsi <DIR>"
+
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "BWA" "$TASK_BWA" "bwa.sh" "$ASD.bam"
+
+        # add as many tables as needed. One table per result file
+        NGSANE_REPORT_TABLE "$TASK_BWA" \
+            "$OUT/<DIR>/$TASK_BWA"  \
+            "$ASD.bam.stats" \
+            "PATTERN:Total reads:sed -n 1p | cut -d' ' -f 1" \
+            "PATTERN:Qfail:sed -n 1p | cut -d' ' -f 3" \
+            "PATTERN:Duplicates:sed -n 2p | cut -d' ' -f 1" \
+            "CALCULATE:Duplicates %:#4*100/#2" \
+            "PATTERN:Mapped:sed -n 3p | cut -d' ' -f 1" \
+            "CALCULATE:Mapped %:#6*100/#2" \
+            "PATTERN:Paired:sed -n 7p | cut -d' ' -f 1" \
+            "CALCULATE:Paired %:#8*100/#2" \
+            "PATTERN:Singletons:sed -n 9p | cut -d' ' -f 1" 
+        
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+        
     fi
-
-    $QSUB $ARMED -k $CONFIG -t $TASK_BWA -i $INPUT_BWA -e $READONE.$FASTQ \
-        -n $NODES_BWA -c $CPU_BWA -m $MEMORY_BWA"G" -w $WALLTIME_BWA $JOBIDS \
-        --command "${NGSANE_BASE}/mods/bwa.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_BWA --rgsi <DIR>"
 fi
diff --git a/mods/run.d/CHANCE b/mods/run.d/CHANCE
--- a/mods/run.d/CHANCE
+++ b/mods/run.d/CHANCE
@@ -7,9 +7,31 @@
 # OUT: $OUT/$dir/chance/
 ################################################################################
 if [ -n "$RUNCHANCE" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_CHANCE" ] || [ -z "$NODES_CHANCE" ] || [ -z "$CPU_CHANCE" ] || [ -z "$MEMORY_CHANCE" ] || [ -z "$WALLTIME_CHANCE" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_CHANCE -i $INPUT_CHANCE -e $ASD.bam \
-        -n $NODES_CHANCE -c $CPU_CHANCE -m $MEMORY_CHANCE"G" -w $WALLTIME_CHANCE \
-        --command "${NGSANE_BASE}/mods/chance.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_CHANCE"
-fi
+        # check if resources are properly defined
+        if [ -z "$TASK_CHANCE" ] || [ -z "$NODES_CHANCE" ] || [ -z "$CPU_CHANCE" ] || [ -z "$MEMORY_CHANCE" ] || [ -z "$WALLTIME_CHANCE" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_CHANCE -i $INPUT_CHANCE -e $ASD.bam \
+            -n $NODES_CHANCE -c $CPU_CHANCE -m $MEMORY_CHANCE"G" -w $WALLTIME_CHANCE \
+            --command "${NGSANE_BASE}/mods/chance.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_CHANCE"
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Chance" "$TASK_CHANCE" "chance.sh"
+
+        echo "[NOTE] the chance.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER  
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/CUFFLINKS b/mods/run.d/CUFFLINKS
--- a/mods/run.d/CUFFLINKS
+++ b/mods/run.d/CUFFLINKS
@@ -8,21 +8,51 @@
 ################################################################################       
 
 if [ -n "$RUNCUFFLINKS" ] || [ -n "$NGSANE_PIPELINECALL" ] ; then
-    if [ -z "$TASK_CUFFLINKS" ] || [ -z "$NODES_CUFFLINKS" ] || [ -z "$CPU_CUFFLINKS" ] || [ -z "$MEMORY_CUFFLINKS" ] || [ -z "$WALLTIME_CUFFLINKS" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-	JOBIDS=$(
-        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_CUFFLINKS -i $INPUT_CUFFLINKS -e $ASD.bam \
-            -n $NODES_CUFFLINKS -c $CPU_CUFFLINKS -m $MEMORY_CUFFLINKS"G" -w $WALLTIME_CUFFLINKS  \
-       		--command "${NGSANE_BASE}/mods/cufflinks.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_CUFFLINKS/<NAME>" \
-       		--postname "postcommandCuffmerge$MERGED_GTF_NAME" \
-        	--postcommand "${NGSANE_BASE}/mods/cuffpost.sh -f <FILE> -k $CONFIG --outdir $OUT/expression/$TASK_CUFFLINKS"
-    	) && echo -e "$JOBIDS"
-    JOBIDS=$(waitForJobIds "$JOBIDS")
+        # check if resources are properly defined
+        if [ -z "$TASK_CUFFLINKS" ] || [ -z "$NODES_CUFFLINKS" ] || [ -z "$CPU_CUFFLINKS" ] || [ -z "$MEMORY_CUFFLINKS" ] || [ -z "$WALLTIME_CUFFLINKS" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    	JOBIDS=$(
+            $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_CUFFLINKS -i $INPUT_CUFFLINKS -e $ASD.bam \
+                -n $NODES_CUFFLINKS -c $CPU_CUFFLINKS -m $MEMORY_CUFFLINKS"G" -w $WALLTIME_CUFFLINKS  \
+           		--command "${NGSANE_BASE}/mods/cufflinks.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_CUFFLINKS/<NAME>" \
+           		--postname "postcommandCuffmerge$MERGED_GTF_NAME" \
+            	--postcommand "${NGSANE_BASE}/mods/cuffpost.sh -f <FILE> -k $CONFIG --outdir $OUT/expression/$TASK_CUFFLINKS"
+        	) && echo -e "$JOBIDS"
+        JOBIDS=$(waitForJobIds "$JOBIDS")
+    
+        $QSUB $ARMED -r -k $CONFIG -t ${TASK_CUFFLINKS}Cuffquant -i $INPUT_CUFFLINKS -e $ASD.bam \
+            -n $NODES_CUFFLINKS -c $CPU_CUFFLINKS -m $MEMORY_CUFFLINKS"G" -w $WALLTIME_CUFFLINKS $JOBIDS \
+    		--command "${NGSANE_BASE}/mods/cuffquant.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_CUFFLINKS/<NAME>" \
+    		--postname "postcommandCuffnorm$MERGED_GTF_NAME" \
+    		--postcommand "${NGSANE_BASE}/mods/cuffnorm.sh -f <FILE> -k $CONFIG --outdir $OUT/expression/$TASK_HTSEQCOUNT"
 
-    $QSUB $ARMED -r -k $CONFIG -t ${TASK_CUFFLINKS}Cuffquant -i $INPUT_CUFFLINKS -e $ASD.bam \
-        -n $NODES_CUFFLINKS -c $CPU_CUFFLINKS -m $MEMORY_CUFFLINKS"G" -w $WALLTIME_CUFFLINKS $JOBIDS \
-		--command "${NGSANE_BASE}/mods/cuffquant.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_CUFFLINKS/<NAME>" \
-		--postname "postcommandCuffnorm$MERGED_GTF_NAME" \
-		--postcommand "${NGSANE_BASE}/mods/cuffnorm.sh -f <FILE> -k $CONFIG --outdir $OUT/expression/$TASK_HTSEQCOUNT"
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Cufflinks" "$TASK_CUTADAPT" "cufflinks.sh,cuffpost.sh"
+
+        echo "[NOTE] the cufflinks.sh,cuffpost.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER  
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Cuffquant" "$TASK_CUTADAPT" "cuffquant.sh,cuffnorm.sh"
+
+        echo "[NOTE] the cuffquant.sh,cuffnorm.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER  
   
-fi
+    fi
+fi	
+
+	
diff --git a/mods/run.d/CUTADAPT b/mods/run.d/CUTADAPT
--- a/mods/run.d/CUTADAPT
+++ b/mods/run.d/CUTADAPT
@@ -8,9 +8,31 @@
 ################################################################################
 
 if [ -n "$RUNCUTADAPT" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_CUTADAPT" ] || [ -z "$NODES_CUTADAPT" ] || [ -z "$CPU_CUTADAPT" ] || [ -z "$MEMORY_CUTADAPT" ] || [ -z "$WALLTIME_CUTADAPT" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
     
-    $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_CUTADAPT -i $INPUT_CUTADAPT -e $READONE.$FASTQ \
-        -n $NODES_CUTADAPT -c $CPU_CUTADAPT -m $MEMORY_CUTADAPT"G" -w $WALLTIME_CUTADAPT \
-        --command "${NGSANE_BASE}/mods/cutadapt.sh -k $CONFIG -f <FILE>" 
-fi
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_CUTADAPT" ] || [ -z "$NODES_CUTADAPT" ] || [ -z "$CPU_CUTADAPT" ] || [ -z "$MEMORY_CUTADAPT" ] || [ -z "$WALLTIME_CUTADAPT" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+        
+        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_CUTADAPT -i $INPUT_CUTADAPT -e $READONE.$FASTQ \
+            -n $NODES_CUTADAPT -c $CPU_CUTADAPT -m $MEMORY_CUTADAPT"G" -w $WALLTIME_CUTADAPT \
+            --command "${NGSANE_BASE}/mods/cutadapt.sh -k $CONFIG -f <FILE>" 
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+    
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Cutadapt" "$TASK_CUTADAPT" "cutadapt.sh"
+
+        echo "[NOTE] the cutadapt.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER   
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/FASTQC b/mods/run.d/FASTQC
--- a/mods/run.d/FASTQC
+++ b/mods/run.d/FASTQC
@@ -7,9 +7,31 @@
 # OUT: $OUT/$dir/fastQC/*
 ################################################################################
 if [ -n "$RUNFASTQC" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_FASTQC" ] || [ -z "$NODES_FASTQC" ] || [ -z "$CPU_FASTQC" ] || [ -z "$MEMORY_FASTQC" ] || [ -z "$WALLTIME_FASTQC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
     
-    $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_FASTQC -i $INPUT_FASTQC -e $READONE.$FASTQ \
-        -n $NODES_FASTQC -c $CPU_FASTQC -m $MEMORY_FASTQC"G" -w $WALLTIME_FASTQC \
-    	--command "${NGSANE_BASE}/mods/fastQC.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FASTQC" 
-fi
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_FASTQC" ] || [ -z "$NODES_FASTQC" ] || [ -z "$CPU_FASTQC" ] || [ -z "$MEMORY_FASTQC" ] || [ -z "$WALLTIME_FASTQC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+        
+        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_FASTQC -i $INPUT_FASTQC -e $READONE.$FASTQ \
+            -n $NODES_FASTQC -c $CPU_FASTQC -m $MEMORY_FASTQC"G" -w $WALLTIME_FASTQC \
+        	--command "${NGSANE_BASE}/mods/fastQC.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FASTQC" 
+
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+    
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "FastQC" "$TASK_FASTQC" "fastQC.sh"
+
+        echo "[NOTE] the fastQC.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER   
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/FASTQSCREEN b/mods/run.d/FASTQSCREEN
--- a/mods/run.d/FASTQSCREEN
+++ b/mods/run.d/FASTQSCREEN
@@ -8,7 +8,33 @@
 ################################################################################
 
 if [ -n "$RUNFASTQSCREEN" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_FASTQSCREEN -i $INPUT_FASTQSCREEN -e $READONE.$FASTQ 
-        -n $NODES_FASTQSCREEN -c $CPU_FASTQSCREEN -m $MEMORY_FASTQSCREEN"G" -w $WALLTIME_FASTQSCREEN \
-        --command "$NGSANE_BASE/mods/fastqscreen.sh -k $CONFIG -f <FILE>  -o $OUT/<DIR>/$TASK_FASTQSCREEN"
-fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_FASTQSCREEN" ] || [ -z "$NODES_FASTQSCREEN" ] || [ -z "$CPU_FASTQSCREEN" ] || [ -z "$MEMORY_FASTQSCREEN" ] || [ -z "$WALLTIME_FASTQSCREEN" ]; then 
+            echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; 
+        fi
+        
+        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_FASTQSCREEN -i $INPUT_FASTQSCREEN -e $READONE.$FASTQ 
+            -n $NODES_FASTQSCREEN -c $CPU_FASTQSCREEN -m $MEMORY_FASTQSCREEN"G" -w $WALLTIME_FASTQSCREEN \
+            --command "$NGSANE_BASE/mods/fastqscreen.sh -k $CONFIG -f <FILE>  -o $OUT/<DIR>/$TASK_FASTQSCREEN"
+        
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Fastqscreen" "$TASK_FASTQSCREEN" "fastqscreen.sh"
+
+        echo "[NOTE] the fastqscreen.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER   
+    fi
+fi	
+
+	
diff --git a/mods/run.d/FITHIC b/mods/run.d/FITHIC
--- a/mods/run.d/FITHIC
+++ b/mods/run.d/FITHIC
@@ -7,10 +7,31 @@
 ################################################################################
 
 if [ -n "$RUNFITHIC" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_FITHIC" ] || [ -z "$NODES_FITHIC" ] || [ -z "$CPU_FITHIC" ] || [ -z "$MEMORY_FITHIC" ] || [ -z "$WALLTIME_FITHIC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_FITHIC -i $INPUT_FITHIC -e $FRAGMENTLIST \
-        -n $NODES_FITHIC -c $CPU_FITHIC -m $MEMORY_FITHIC"G" -w $WALLTIME_FITHIC \
-        --command "${NGSANE_BASE}/mods/fithic.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FITHIC"
+        # check if resources are properly defined
+        if [ -z "$TASK_FITHIC" ] || [ -z "$NODES_FITHIC" ] || [ -z "$CPU_FITHIC" ] || [ -z "$MEMORY_FITHIC" ] || [ -z "$WALLTIME_FITHIC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_FITHIC -i $INPUT_FITHIC -e $FRAGMENTLIST \
+            -n $NODES_FITHIC -c $CPU_FITHIC -m $MEMORY_FITHIC"G" -w $WALLTIME_FITHIC \
+            --command "${NGSANE_BASE}/mods/fithic.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_FITHIC"
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
 
-fi
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Fithic" "$TASK_FITHIC" "fithic.sh"
+
+        echo "[NOTE] the fithic.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/HICLIB b/mods/run.d/HICLIB
--- a/mods/run.d/HICLIB
+++ b/mods/run.d/HICLIB
@@ -8,25 +8,48 @@
 ################################################################################
 
 if [ -n "$RUNHICLIB" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_HICLIB" ] || [ -z "$NODES_HICLIB" ] || [ -z "$CPU_HICLIB" ] || [ -z "$MEMORY_HICLIB" ] || [ -z "$WALLTIME_HICLIB" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
-
-    if [ ! -f ${FASTA%.*}.1.bt2 ];then
-        # submit job for index generation if necessary
-        INDEXJOBIDS=$(
-            $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_HICLIB -i $INPUT_HICLIB -e $READONE.$FASTQ 
-            -n $NODES_HICLIB -c $CPU_HICLIB -m $MEMORY_HICLIB"G" \
-            -w $WALLTIME_HICLIB --commontask indexGenome \
-            --command "${NGSANE_BASE}/mods/bowtie2Index.sh -k $CONFIG"
-        ) && echo -e "$INDEXJOBIDS"
-        INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
-    else
-        INDEXJOBIDS=$NGSANE_WAITFORJOB 
-    fi
     
-    $QSUB $ARMED -k $CONFIG -t $TASK_HICLIB -i $INPUT_HICLIB -e $READONE.$FASTQ \
-    	-n $NODES_HICLIB -c $CPU_HICLIB -m $MEMORY_HICLIB"G" -w $WALLTIME_HICLIB \
-    	--postnodes $NODES_HICLIB_POSTCOMMAND \
-    	--postcpu $CPU_HICLIB_POSTCOMMAND $INDEXJOBIDS \
-        --command "${NGSANE_BASE}/mods/hiclibMapping.sh -k $CONFIG --fastq <FILE> --outdir $OUT/<DIR>/$TASK_HICLIB" \
-        --postcommand "${NGSANE_BASE}/mods/hiclibCorrelate.sh -f <FILE> -k $CONFIG --outdir $OUT/$TASK_HICLIB/$TASK_HICLIB-<DIR>"
-fi
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_HICLIB" ] || [ -z "$NODES_HICLIB" ] || [ -z "$CPU_HICLIB" ] || [ -z "$MEMORY_HICLIB" ] || [ -z "$WALLTIME_HICLIB" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        if [ ! -f ${FASTA%.*}.1.bt2 ];then
+            # submit job for index generation if necessary
+            INDEXJOBIDS=$(
+                $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_HICLIB -i $INPUT_HICLIB -e $READONE.$FASTQ 
+                -n $NODES_HICLIB -c $CPU_HICLIB -m $MEMORY_HICLIB"G" \
+                -w $WALLTIME_HICLIB --commontask indexGenome \
+                --command "${NGSANE_BASE}/mods/bowtie2Index.sh -k $CONFIG"
+            ) && echo -e "$INDEXJOBIDS"
+            INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
+        else
+            INDEXJOBIDS=$NGSANE_WAITFORJOB 
+        fi
+        
+        $QSUB $ARMED -k $CONFIG -t $TASK_HICLIB -i $INPUT_HICLIB -e $READONE.$FASTQ \
+        	-n $NODES_HICLIB -c $CPU_HICLIB -m $MEMORY_HICLIB"G" -w $WALLTIME_HICLIB \
+        	--postnodes $NODES_HICLIB_POSTCOMMAND \
+        	--postcpu $CPU_HICLIB_POSTCOMMAND $INDEXJOBIDS \
+            --command "${NGSANE_BASE}/mods/hiclibMapping.sh -k $CONFIG --fastq <FILE> --outdir $OUT/<DIR>/$TASK_HICLIB" \
+            --postcommand "${NGSANE_BASE}/mods/hiclibCorrelate.sh -f <FILE> -k $CONFIG --outdir $OUT/$TASK_HICLIB/$TASK_HICLIB-<DIR>"
+        
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Hiclib" "$TASK_HICLIB" "hiclibMapping.sh,hiclibCorrelate.sh"
+
+        echo "[NOTE] the hiclibMapping.sh,hiclibCorrelate.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/HICUP b/mods/run.d/HICUP
--- a/mods/run.d/HICUP
+++ b/mods/run.d/HICUP
@@ -7,36 +7,57 @@
 ################################################################################
 
 if [ -n "$RUNHICUP" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_HICUP" ] || [ -z "$NODES_HICUP" ] || [ -z "$CPU_HICUP" ] || [ -z "$MEMORY_HICUP" ] || [ -z "$WALLTIME_HICUP" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
     
-    if [ ! -f ${FASTA%.*}.1.ebwt ];then
-        # submit job for index generation if necessary
-        INDEXJOBIDS=$(
-            $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_HICUP -i $INPUT_HICUP -e $READONE.$FASTQ -n $NODES_HICUP -c $CPU_HICUP \
-    	   -m $MEMORY_HICUP"G" -w $WALLTIME_HICUP \
-    	   --commontask indexGenome \
-           --command "${NGSANE_BASE}/mods/bowtieIndex.sh -k $CONFIG"
-        ) && echo -e "$INDEXJOBIDS"
-        INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
-    else
-        INDEXJOBIDS=$NGSANE_WAITFORJOB 
-    fi
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_HICUP" ] || [ -z "$NODES_HICUP" ] || [ -z "$CPU_HICUP" ] || [ -z "$MEMORY_HICUP" ] || [ -z "$WALLTIME_HICUP" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+        
+        if [ ! -f ${FASTA%.*}.1.ebwt ];then
+            # submit job for index generation if necessary
+            INDEXJOBIDS=$(
+                $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_HICUP -i $INPUT_HICUP -e $READONE.$FASTQ -n $NODES_HICUP -c $CPU_HICUP \
+        	   -m $MEMORY_HICUP"G" -w $WALLTIME_HICUP \
+        	   --commontask indexGenome \
+               --command "${NGSANE_BASE}/mods/bowtieIndex.sh -k $CONFIG"
+            ) && echo -e "$INDEXJOBIDS"
+            INDEXJOBIDS=$(waitForJobIds "$INDEXJOBIDS")
+        else
+            INDEXJOBIDS=$NGSANE_WAITFORJOB 
+        fi
+        
+        if [ ! -f $OUT/common/$TASK_HICUP/Digest_${REFERENCE_NAME}_${HICUP_RENZYME1}_${HICUP_RENZYME2}.txt ];then
+            JOBIDS=$( 
+            $QSUB $ARMED -k $CONFIG -t $TASK_HICUP -i $INPUT_HICUP -e $READONE.$FASTQ -n $NODES_HICUP -c 1 \
+            	-m $MEMORY_HICUP"G" -w $WALLTIME_HICUP $INDEXJOBIDS $WAITFORJOB_HICUP \
+            	--commontask digestGenome \
+                --command "${NGSANE_BASE}/mods/hicupDigestGenome.sh -k $CONFIG" 
+            ) && echo -e "$JOBIDS"
+            JOBIDS=$(waitForJobIds "$JOBIDS")
     
-    if [ ! -f $OUT/common/$TASK_HICUP/Digest_${REFERENCE_NAME}_${HICUP_RENZYME1}_${HICUP_RENZYME2}.txt ];then
-        JOBIDS=$( 
-        $QSUB $ARMED -k $CONFIG -t $TASK_HICUP -i $INPUT_HICUP -e $READONE.$FASTQ -n $NODES_HICUP -c 1 \
-        	-m $MEMORY_HICUP"G" -w $WALLTIME_HICUP $INDEXJOBIDS $WAITFORJOB_HICUP \
-        	--commontask digestGenome \
-            --command "${NGSANE_BASE}/mods/hicupDigestGenome.sh -k $CONFIG" 
-        ) && echo -e "$JOBIDS"
-        JOBIDS=$(waitForJobIds "$JOBIDS")
+        else
+            JOBIDS=$WAITFORJOB_HICUP
+        fi
+    
+        $QSUB $ARMED -k $CONFIG -t $TASK_HICUP -i $INPUT_HICUP -e $READONE.$FASTQ -n $NODES_HICUP -c $CPU_HICUP \
+        	-m $MEMORY_HICUP"G" -w $WALLTIME_HICUP $JOBIDS \
+            --command "${NGSANE_BASE}/mods/hicup.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HICUP"
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
 
-    else
-        JOBIDS=$WAITFORJOB_HICUP
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "HiCuP" "$TASK_HICUP" "hicup.sh"
+
+        echo "[NOTE] the hicup.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+  
     fi
+fi	
 
-    $QSUB $ARMED -k $CONFIG -t $TASK_HICUP -i $INPUT_HICUP -e $READONE.$FASTQ -n $NODES_HICUP -c $CPU_HICUP \
-    	-m $MEMORY_HICUP"G" -w $WALLTIME_HICUP $JOBIDS \
-        --command "${NGSANE_BASE}/mods/hicup.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HICUP"
-
-fi
+	
diff --git a/mods/run.d/HOMERCHIPSEQ b/mods/run.d/HOMERCHIPSEQ
--- a/mods/run.d/HOMERCHIPSEQ
+++ b/mods/run.d/HOMERCHIPSEQ
@@ -7,22 +7,44 @@
 # OUT: $OUT/$dir/homerchipseq/
 ################################################################################
 if [ -n "$RUNHOMERCHIPSEQ" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_HOMERCHIPSEQ" ] || [ -z "$NODES_HOMERCHIPSEQ" ] || [ -z "$CPU_HOMERCHIPSEQ" ] || [ -z "$MEMORY_HOMERCHIPSEQ" ] || [ -z "$WALLTIME_HOMERCHIPSEQ" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
-
-    if  [ -n "$CHIPINPUT" ];then
-        JOBIDS=$( 
-        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_HOMERCHIPSEQ -i $INPUT_HOMERCHIPSEQ -e $ASD.bam \
-            -n $NODES_HOMERCHIPSEQ -c $CPU_HOMERCHIPSEQ -m $MEMORY_HOMERCHIPSEQ"G" -w $WALLTIME_HOMERCHIPSEQ \
-            --commontask ${CONFIG##*/} \
-            --command "${NGSANE_BASE}/mods/chipseqHomerInput.sh -k $CONFIG" 
-        ) && echo -e "$JOBIDS"
-        JOBIDS=$(waitForJobIds "$JOBIDS")
-
-    else
-        JOBIDS=$NGSANE_WAITFORJOB 
-    fi
     
-    $QSUB $ARMED -r -k $CONFIG -t $TASK_HOMERCHIPSEQ -i $INPUT_HOMERCHIPSEQ -e $ASD.bam \
-        -n $NODES_HOMERCHIPSEQ -c $CPU_HOMERCHIPSEQ -m $MEMORY_HOMERCHIPSEQ"G" -w $WALLTIME_HOMERCHIPSEQ $JOBIDS \
-        --command "${NGSANE_BASE}/mods/chipseqHomer.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HOMERCHIPSEQ"
-fi
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_HOMERCHIPSEQ" ] || [ -z "$NODES_HOMERCHIPSEQ" ] || [ -z "$CPU_HOMERCHIPSEQ" ] || [ -z "$MEMORY_HOMERCHIPSEQ" ] || [ -z "$WALLTIME_HOMERCHIPSEQ" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        if  [ -n "$CHIPINPUT" ];then
+            JOBIDS=$( 
+            $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_HOMERCHIPSEQ -i $INPUT_HOMERCHIPSEQ -e $ASD.bam \
+                -n $NODES_HOMERCHIPSEQ -c $CPU_HOMERCHIPSEQ -m $MEMORY_HOMERCHIPSEQ"G" -w $WALLTIME_HOMERCHIPSEQ \
+                --commontask ${CONFIG##*/} \
+                --command "${NGSANE_BASE}/mods/chipseqHomerInput.sh -k $CONFIG" 
+            ) && echo -e "$JOBIDS"
+            JOBIDS=$(waitForJobIds "$JOBIDS")
+    
+        else
+            JOBIDS=$NGSANE_WAITFORJOB 
+        fi
+        
+        $QSUB $ARMED -r -k $CONFIG -t $TASK_HOMERCHIPSEQ -i $INPUT_HOMERCHIPSEQ -e $ASD.bam \
+            -n $NODES_HOMERCHIPSEQ -c $CPU_HOMERCHIPSEQ -m $MEMORY_HOMERCHIPSEQ"G" -w $WALLTIME_HOMERCHIPSEQ $JOBIDS \
+            --command "${NGSANE_BASE}/mods/chipseqHomer.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HOMERCHIPSEQ"
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Homer ChIP-seq" "$TASK_HOMERCHIPSEQ" "chipseqHomer.sh"
+
+        echo "[NOTE] the chipseqHomer.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/HOPSPOT b/mods/run.d/HOPSPOT
--- a/mods/run.d/HOPSPOT
+++ b/mods/run.d/HOPSPOT
@@ -8,9 +8,32 @@
 ################################################################################       
 
 if [ -n "$RUNHOTSPOT" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_HOTSPOT" ] || [ -z "$NODES_HOTSPOT" ] || [ -z "$CPU_HOTSPOT" ] || [ -z "$MEMORY_HOTSPOT" ] || [ -z "$WALLTIME_HOTSPOT" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
     
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_HOTSPOT -i $INPUT_HOTSPOT -e $ASD.bam \
-        -n $NODES_HOTSPOT -c $CPU_HOTSPOT -m $MEMORY_HOTSPOT"G" -w $WALLTIME_HOTSPOT \
-        --command "${NGSANE_BASE}/mods/hotspot.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HOTSPOT"
-fi
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_HOTSPOT" ] || [ -z "$NODES_HOTSPOT" ] || [ -z "$CPU_HOTSPOT" ] || [ -z "$MEMORY_HOTSPOT" ] || [ -z "$WALLTIME_HOTSPOT" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+        
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_HOTSPOT -i $INPUT_HOTSPOT -e $ASD.bam \
+            -n $NODES_HOTSPOT -c $CPU_HOTSPOT -m $MEMORY_HOTSPOT"G" -w $WALLTIME_HOTSPOT \
+            --command "${NGSANE_BASE}/mods/hotspot.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HOTSPOT"
+
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Hotspot" "$TASK_HOTSPOT" "hotspot.sh"
+
+        echo "[NOTE] the hotspot.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/HTSEQCOUNT b/mods/run.d/HTSEQCOUNT
--- a/mods/run.d/HTSEQCOUNT
+++ b/mods/run.d/HTSEQCOUNT
@@ -8,11 +8,34 @@
 ################################################################################       
 
 if [ -n "$RUNHTSEQCOUNT" ] || [ -n "$NGSANE_PIPELINECALL" ] ; then
-    if [ -z "$TASK_HTSEQCOUNT" ] || [ -z "$NODES_HTSEQCOUNT" ] || [ -z "$CPU_HTSEQCOUNT" ] || [ -z "$MEMORY_HTSEQCOUNT" ] || [ -z "$WALLTIME_HTSEQCOUNT" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_HTSEQCOUNT -i $INPUT_HTSEQCOUNT -e $ASD.bam \
-        -n $NODES_HTSEQCOUNT -c $CPU_HTSEQCOUNT -m $MEMORY_HTSEQCOUNT"G" -w $WALLTIME_HTSEQCOUNT \
-        --command "${NGSANE_BASE}/mods/htseqcount.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HTSEQCOUNT/<NAME>" \
-        --postname "postcommandHtseq$HTSEQCOUNT_TABLE_FOLDERNAME" \
-        --postcommand "${NGSANE_BASE}/mods/countsTable.sh -f <FILE> -k $CONFIG --outdir $OUT/expression/$HTSEQCOUNT_TABLE_FOLDERNAME"
-fi
+        # check if resources are properly defined
+        if [ -z "$TASK_HTSEQCOUNT" ] || [ -z "$NODES_HTSEQCOUNT" ] || [ -z "$CPU_HTSEQCOUNT" ] || [ -z "$MEMORY_HTSEQCOUNT" ] || [ -z "$WALLTIME_HTSEQCOUNT" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_HTSEQCOUNT -i $INPUT_HTSEQCOUNT -e $ASD.bam \
+            -n $NODES_HTSEQCOUNT -c $CPU_HTSEQCOUNT -m $MEMORY_HTSEQCOUNT"G" -w $WALLTIME_HTSEQCOUNT \
+            --command "${NGSANE_BASE}/mods/htseqcount.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_HTSEQCOUNT/<NAME>" \
+            --postname "postcommandHtseq$HTSEQCOUNT_TABLE_FOLDERNAME" \
+            --postcommand "${NGSANE_BASE}/mods/countsTable.sh -f <FILE> -k $CONFIG --outdir $OUT/expression/$HTSEQCOUNT_TABLE_FOLDERNAME"
+
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Htseqcount" "$TASK_HTSEQCOUNT" "htseqcount.sh,countsTable.sh"
+
+        echo "[NOTE] the htseqcount.sh,countsTable.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/MACS2 b/mods/run.d/MACS2
--- a/mods/run.d/MACS2
+++ b/mods/run.d/MACS2
@@ -7,9 +7,31 @@
 # OUT: $OUT/$dir/macs2/
 ################################################################################
 if [ -n "$RUNMACS2" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_MACS2" ] || [ -z "$NODES_MACS2" ] || [ -z "$CPU_MACS2" ] || [ -z "$MEMORY_MACS2" ] || [ -z "$WALLTIME_MACS2" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_MACS2 -i $INPUT_MACS2 -e $ASD.bam \
-        -n $NODES_MACS2 -c $CPU_MACS2 -m $MEMORY_MACS2"G" -w $WALLTIME_MACS2 \
-        --command "${NGSANE_BASE}/mods/macs2.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_MACS2"
-fi
+        # check if resources are properly defined
+        if [ -z "$TASK_MACS2" ] || [ -z "$NODES_MACS2" ] || [ -z "$CPU_MACS2" ] || [ -z "$MEMORY_MACS2" ] || [ -z "$WALLTIME_MACS2" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_MACS2 -i $INPUT_MACS2 -e $ASD.bam \
+            -n $NODES_MACS2 -c $CPU_MACS2 -m $MEMORY_MACS2"G" -w $WALLTIME_MACS2 \
+            --command "${NGSANE_BASE}/mods/macs2.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_MACS2"
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Macs2" "$TASK_MACS2" "macs2.sh"
+
+        echo "[NOTE] the macs2.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/MEMECHIP b/mods/run.d/MEMECHIP
--- a/mods/run.d/MEMECHIP
+++ b/mods/run.d/MEMECHIP
@@ -7,9 +7,32 @@
 # OUT: $OUT/$dir/memechip/
 ################################################################################
 if [ -n "$RUNMEMECHIP" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_MEMECHIP" ] || [ -z "$NODES_MEMECHIP" ] || [ -z "$CPU_MEMECHIP" ] || [ -z "$MEMORY_MEMECHIP" ] || [ -z "$WALLTIME_MEMECHIP" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_MEMECHIP -i $INPUT_MEMECHIP -e $BED \
-    -n $NODES_MEMECHIP -c $CPU_MEMECHIP -m $MEMORY_MEMECHIP"G" -w $WALLTIME_MEMECHIP \
-	   --command "${NGSANE_BASE}/mods/memechip.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_MEMECHIP"
-fi
+        # check if resources are properly defined
+        if [ -z "$TASK_MEMECHIP" ] || [ -z "$NODES_MEMECHIP" ] || [ -z "$CPU_MEMECHIP" ] || [ -z "$MEMORY_MEMECHIP" ] || [ -z "$WALLTIME_MEMECHIP" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_MEMECHIP -i $INPUT_MEMECHIP -e $BED \
+            -n $NODES_MEMECHIP -c $CPU_MEMECHIP -m $MEMORY_MEMECHIP"G" -w $WALLTIME_MEMECHIP \
+    	   --command "${NGSANE_BASE}/mods/memechip.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_MEMECHIP"
+    	   
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "MemeChip" "$TASK_MEMECHIP" "memechip.sh"
+
+        echo "[NOTE] the memechip.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/PEAKRANGER b/mods/run.d/PEAKRANGER
--- a/mods/run.d/PEAKRANGER
+++ b/mods/run.d/PEAKRANGER
@@ -7,9 +7,31 @@
 # OUT: $OUT/$dir/peakranger/
 ################################################################################
 if [ -n "$RUNPEAKRANGER" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_PEAKRANGER" ] || [ -z "$NODES_PEAKRANGER" ] || [ -z "$CPU_PEAKRANGER" ] || [ -z "$MEMORY_PEAKRANGER" ] || [ -z "$WALLTIME_PEAKRANGER" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_PEAKRANGER -i $INPUT_PEAKRANGER -e $ASD.bam \
-        -n $NODES_PEAKRANGER -c $CPU_PEAKRANGER -m $MEMORY_PEAKRANGER"G" -w $WALLTIME_PEAKRANGER \
-	   --command "${NGSANE_BASE}/mods/peakranger.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_PEAKRANGER"
-fi
+        # check if resources are properly defined
+        if [ -z "$TASK_PEAKRANGER" ] || [ -z "$NODES_PEAKRANGER" ] || [ -z "$CPU_PEAKRANGER" ] || [ -z "$MEMORY_PEAKRANGER" ] || [ -z "$WALLTIME_PEAKRANGER" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_PEAKRANGER -i $INPUT_PEAKRANGER -e $ASD.bam \
+            -n $NODES_PEAKRANGER -c $CPU_PEAKRANGER -m $MEMORY_PEAKRANGER"G" -w $WALLTIME_PEAKRANGER \
+            --command "${NGSANE_BASE}/mods/peakranger.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_PEAKRANGER"
+            
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Peakranger" "$TASK_PEAKRANGER" "peakranger.sh"
+
+        echo "[NOTE] the peakranger.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+  
+    fi
+fi	
+
+	
diff --git a/mods/run.d/POOLBAMS b/mods/run.d/POOLBAMS
--- a/mods/run.d/POOLBAMS
+++ b/mods/run.d/POOLBAMS
@@ -1,6 +1,5 @@
 #!/bin/bash -e
 
-
 ################################################################################
 #   Pool bam files (e.g. replicates)
 #
@@ -9,10 +8,43 @@
 ################################################################################
 
 if [ -n "$RUNPOOLBAMS" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_POOLBAMS" ] || [ -z "$NODES_POOLBAMS" ] || [ -z "$CPU_POOLBAMS" ] || [ -z "$MEMORY_POOLBAMS" ] || [ -z "$WALLTIME_POOLBAMS" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
     
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -d -k $CONFIG -t $TASK_POOLBAMS -i $INPUT_POOLBAMS -e $ASD.bam -n $NODES_POOLBAMS \
-    	-c $CPU_POOLBAMS -m $MEMORY_POOLBAMS"G" -w $WALLTIME_POOLBAMS \
-    	--postname postcommand${POOLED_DATA_NAME} \
-    	--postcommand "${NGSANE_BASE}/mods/poolBams.sh -k $CONFIG --outdir $OUT/<DIR>/$TASK_POOLBAMS" 
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined
+        if [ -z "$TASK_POOLBAMS" ] || [ -z "$NODES_POOLBAMS" ] || [ -z "$CPU_POOLBAMS" ] || [ -z "$MEMORY_POOLBAMS" ] || [ -z "$WALLTIME_POOLBAMS" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+        
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -d -k $CONFIG -t $TASK_POOLBAMS -i $INPUT_POOLBAMS -e $ASD.bam -n $NODES_POOLBAMS \
+        	-c $CPU_POOLBAMS -m $MEMORY_POOLBAMS"G" -w $WALLTIME_POOLBAMS \
+        	--postname postcommand${POOLED_DATA_NAME} \
+        	--postcommand "${NGSANE_BASE}/mods/poolBams.sh -k $CONFIG --outdir $OUT/<DIR>/$TASK_POOLBAMS" 
+        	
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Pool Bams" "$TASK_POOLBAMS" "bowtie2.sh" "$ASD.bam"
+
+        # add as many tables as needed. One table per result file
+        NGSANE_REPORT_TABLE "$TASK_POOLBAMS" \
+            "$OUT/<DIR>/$TASK_POOLBAMS"  \
+            "$ASD.bam.stats" \
+            "PATTERN:Total reads:sed -n 1p | cut -d' ' -f 1" \
+            "PATTERN:Qfail:sed -n 1p | cut -d' ' -f 3" \
+            "PATTERN:Duplicates:sed -n 2p | cut -d' ' -f 1" \
+            "CALCULATE:Duplicates %:#4*100/#2" \
+            "PATTERN:Mapped:sed -n 3p | cut -d' ' -f 1" \
+            "CALCULATE:Mapped %:#6*100/#2" \
+            "PATTERN:Paired:sed -n 7p | cut -d' ' -f 1" \
+            "CALCULATE:Paired %:#8*100/#2" \
+            "PATTERN:Singletons:sed -n 9p | cut -d' ' -f 1" 
+        
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+        
+    fi
 fi
diff --git a/mods/run.d/QUALIMAP b/mods/run.d/QUALIMAP
--- a/mods/run.d/QUALIMAP
+++ b/mods/run.d/QUALIMAP
@@ -8,10 +8,31 @@
 ################################################################################       
 
 if [ -n "$RUNQUALIMAP" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_QUALIMAP" ] || [ -z "$NODES_QUALIMAP" ] || [ -z "$CPU_QUALIMAP" ] || [ -z "$MEMORY_QUALIMAP" ] || [ -z "$WALLTIME_QUALIMAP" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_QUALIMAP -i $INPUT_QUALIMAP -e $ASD.bam \
-    -n $NODES_QUALIMAP -c $CPU_QUALIMAP -m $MEMORY_QUALIMAP"G" -w $WALLTIME_QUALIMAP \
-        --command "${NGSANE_BASE}/mods/qualimap.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_QUALIMAP/"
+        # check if resources are properly defined
+        if [ -z "$TASK_QUALIMAP" ] || [ -z "$NODES_QUALIMAP" ] || [ -z "$CPU_QUALIMAP" ] || [ -z "$MEMORY_QUALIMAP" ] || [ -z "$WALLTIME_QUALIMAP" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_QUALIMAP -i $INPUT_QUALIMAP -e $ASD.bam \
+            -n $NODES_QUALIMAP -c $CPU_QUALIMAP -m $MEMORY_QUALIMAP"G" -w $WALLTIME_QUALIMAP \
+            --command "${NGSANE_BASE}/mods/qualimap.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_QUALIMAP/"
 
-fi
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "QualiMap" "$TASK_QUALIMAP" "qualimap.sh"
+
+        echo "[NOTE] the qualimap.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+        
+    fi
+fi	
+
+	
diff --git a/mods/run.d/RNASEQC b/mods/run.d/RNASEQC
--- a/mods/run.d/RNASEQC
+++ b/mods/run.d/RNASEQC
@@ -8,10 +8,31 @@
 ################################################################################       
 
 if [ -n "$RUNRNASEQC" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_RNASEQC" ] || [ -z "$NODES_RNASEQC" ] || [ -z "$CPU_RNASEQC" ] || [ -z "$MEMORY_RNASEQC" ] || [ -z "$WALLTIME_RNASEQC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_RNASEQC -i $INPUT_RNASEQC -e $ASD.bam \
-        -n $NODES_RNASEQC -c $CPU_RNASEQC -m $MEMORY_RNASEQC"G" -w $WALLTIME_RNASEQC \
-        --command "${NGSANE_BASE}/mods/rnaseqc.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_RNASEQC/<NAME>"
+        # check if resources are properly defined
+        if [ -z "$TASK_RNASEQC" ] || [ -z "$NODES_RNASEQC" ] || [ -z "$CPU_RNASEQC" ] || [ -z "$MEMORY_RNASEQC" ] || [ -z "$WALLTIME_RNASEQC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -r -k $CONFIG -t $TASK_RNASEQC -i $INPUT_RNASEQC -e $ASD.bam \
+            -n $NODES_RNASEQC -c $CPU_RNASEQC -m $MEMORY_RNASEQC"G" -w $WALLTIME_RNASEQC \
+            --command "${NGSANE_BASE}/mods/rnaseqc.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_RNASEQC/<NAME>"
 
-fi
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "RNA-SeQC" "$TASK_RNASEQC" "rnaseqc.sh"
+
+        echo "[NOTE] the rnaseqc.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+    fi
+fi	
+
+	
diff --git a/mods/run.d/RRBS b/mods/run.d/RRBS
--- a/mods/run.d/RRBS
+++ b/mods/run.d/RRBS
@@ -8,10 +8,32 @@
 ################################################################################
 
 if [ -n "$RUNRRBS" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_RRBSMAP" ] || [ -z "$NODES_RRBSMAP" ] || [ -z "$CPU_RRBSMAP" ] || [ -z "$MEMORY_RRBSMAP" ] || [ -z "$WALLTIME_RRBSMAP" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_RRBSMAP -i $INPUT_RRBSMAP -e $READONE.$FASTQ \
-    -n $NODES_RRBSMAP -c $CPU_RRBSMAP -m $MEMORY_RRBSMAP"G" -w $WALLTIME_RRBSMAP \
-    --command "${NGSANE_BASE}/mods/rrbsmap.sh -k $CONFIG -f <FILE> -r $FASTA \
-        -o $OUT/<DIR>/$TASK_RRBSMAP --rgid $EXPID --rglb $LIBRARY --rgpl $PLATFORM --rgsi <DIR>"
-fi
+        # check if resources are properly defined
+        if [ -z "$TASK_RRBSMAP" ] || [ -z "$NODES_RRBSMAP" ] || [ -z "$CPU_RRBSMAP" ] || [ -z "$MEMORY_RRBSMAP" ] || [ -z "$WALLTIME_RRBSMAP" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_RRBSMAP -i $INPUT_RRBSMAP -e $READONE.$FASTQ \
+            -n $NODES_RRBSMAP -c $CPU_RRBSMAP -m $MEMORY_RRBSMAP"G" -w $WALLTIME_RRBSMAP \
+            --command "${NGSANE_BASE}/mods/rrbsmap.sh -k $CONFIG -f <FILE> -r $FASTA \
+                -o $OUT/<DIR>/$TASK_RRBSMAP --rgid $EXPID --rglb $LIBRARY --rgpl $PLATFORM --rgsi <DIR>"
+    
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Rrbs" "$TASK_RRBSMAP" "rrbsmap.sh"
+
+        echo "[NOTE] the rrbsmap.sh mod does not provide a report"
+
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+        
+    fi
+fi	
+
+	
diff --git a/mods/run.d/TRIMMOMATIC b/mods/run.d/TRIMMOMATIC
--- a/mods/run.d/TRIMMOMATIC
+++ b/mods/run.d/TRIMMOMATIC
@@ -8,9 +8,31 @@
 ################################################################################
 
 if [ -n "$RUNTRIMMOMATIC" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$TASK_TRIMMOMATIC" ] || [ -z "$NODES_TRIMMOMATIC" ] || [ -z "$CPU_TRIMMOMATIC" ] || [ -z "$MEMORY_TRIMMOMATIC" ] || [ -z "$WALLTIME_TRIMMOMATIC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
     
-    $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_TRIMMOMATIC -i $INPUT_TRIMMOMATIC -e $READONE.$FASTQ -n $NODES_TRIMMOMATIC \
-        -c $CPU_TRIMMOMATIC -m $MEMORY_TRIMMOMATIC"G" -w $WALLTIME_TRIMMOMATIC \
-        --command "$NGSANE_BASE/mods/trimmomatic.sh -k $CONFIG -f <FILE>"
-fi
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        # check if resources are properly defined       
+        if [ -z "$TASK_TRIMMOMATIC" ] || [ -z "$NODES_TRIMMOMATIC" ] || [ -z "$CPU_TRIMMOMATIC" ] || [ -z "$MEMORY_TRIMMOMATIC" ] || [ -z "$WALLTIME_TRIMMOMATIC" ]; then echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+        
+        $QSUB $ARMED $NGSANE_WAITFORJOB -d -k $CONFIG -t $TASK_TRIMMOMATIC -i $INPUT_TRIMMOMATIC -e $READONE.$FASTQ -n $NODES_TRIMMOMATIC \
+            -c $CPU_TRIMMOMATIC -m $MEMORY_TRIMMOMATIC"G" -w $WALLTIME_TRIMMOMATIC \
+            --command "$NGSANE_BASE/mods/trimmomatic.sh -k $CONFIG -f <FILE>"
+            
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Trimmomatic" "$TASK_TRIMMOMATIC" "trimmomatic.sh"
+
+        echo "[NOTE] the trimmomatic.sh mod does not provide a report"
+  
+          # finish the section
+        NGSANE_REPORT_FOOTER 
+     
+    fi
+fi	
+
+	
diff --git a/mods/run.d/TRINITY_INCHWORM b/mods/run.d/TRINITY_INCHWORM
--- a/mods/run.d/TRINITY_INCHWORM
+++ b/mods/run.d/TRINITY_INCHWORM
@@ -6,13 +6,32 @@
 # OUT: $OUT/$dir/trinity/*.Trinity.fasta.gz
 ################################################################################
 
-################################################################################
-# individual calls
 #  ##########   Inchworm   ###########
 if [ -n "$RUNINCHWORM" ] || [ -n "$NGSANE_PIPELINECALL" ]; then
-    if [ -z "$NODES_INCHWORM" ] || [ -z "$NCPU_INCHWORM" ] || [ -z "$MEMORY_INCHWORM" ] || [ -z "$WALLTIME_INCHWORM" ] || [ -z "$NODETYPE_INCHWORM" ]; then  echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
 
-    $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_INCHWORM -i $INPUT_INCHWORM -e $READONE.$FASTQ -n $NODES_INCHWORM \
-        -c $NCPU_INCHWORM -m $MEMORY_INCHWORM"G" -w $WALLTIME_INCHWORM -q $NODETYPE_INCHWORM \
-        --command "${NGSANE_BASE}/mods/trinity_inchworm.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_INCHWORM"
-fi
+    ############################################################################
+    # Wether to submit a job or compile a report
+    if [ -z "$NGSANE_COMPILE_REPORT" ]; then
+
+        if [ -z "$NODES_INCHWORM" ] || [ -z "$NCPU_INCHWORM" ] || [ -z "$MEMORY_INCHWORM" ] || [ -z "$WALLTIME_INCHWORM" ] || [ -z "$NODETYPE_INCHWORM" ]; then  echo -e "\e[91m[ERROR]\e[0m Server misconfigured"; exit 1; fi
+    
+        $QSUB $ARMED $NGSANE_WAITFORJOB -k $CONFIG -t $TASK_INCHWORM -i $INPUT_INCHWORM -e $READONE.$FASTQ -n $NODES_INCHWORM \
+            -c $NCPU_INCHWORM -m $MEMORY_INCHWORM"G" -w $WALLTIME_INCHWORM -q $NODETYPE_INCHWORM \
+            --command "${NGSANE_BASE}/mods/trinity_inchworm.sh -k $CONFIG -f <FILE> -o $OUT/<DIR>/$TASK_INCHWORM"
+            
+    ############################################################################
+    # compile a report for this mod
+    elif [ -n "$NGSANE_COMPILE_REPORT" ]; then
+
+        # start a new section for a mod
+        NGSANE_REPORT_HEADER "Trinity Inchworm" "$TASK_INCHWORM" "trinity_inchworm.sh"
+
+        echo "[NOTE] the trinity_inchworm.sh mod does not provide a report"
+        
+        # finish the section
+        NGSANE_REPORT_FOOTER 
+        
+    fi
+fi	
+
+	
